#pragma once

#include "ap_version.h"

#define THISFIRMWARE "GLADoS V0.1.3.3AXTON"
#define FIRMWARE_VERSION 3,8,5,FIRMWARE_VERSION_TYPE_BETA

#ifndef GIT_VERSION
#define FIRMWARE_STRING THISFIRMWARE
#else
#define FIRMWARE_STRING THISFIRMWARE " (" GIT_VERSION ")"
#endif
